# Generated by Django 5.0.3 on 2024-05-10 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_origen', models.CharField(default='', max_length=100)),
                ('direccion_destino', models.CharField(default='', max_length=100)),
                ('hora_salida', models.DateTimeField()),
                ('vehiculo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='PasajeroViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.customuser')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viaje.viaje')),
            ],
        ),
    ]
