# Generated by Django 5.0.3 on 2024-05-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(choices=[('Conductor', 'Conductor'), ('Pasajero', 'Pasajero')], default='Pasajero', max_length=10)),
                ('valor_calificacion', models.IntegerField(default='')),
                ('comentario', models.TextField(default='')),
                ('pasajero_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viaje.pasajeroviaje')),
            ],
        ),
    ]
