# Generated by Django 5.0.3 on 2024-05-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0002_alter_calificacion_valor_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(default='', max_length=300),
        ),
    ]
