# Generated by Django 5.0.3 on 2024-05-09 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(default='', max_length=50)),
                ('marca', models.CharField(default='', max_length=50)),
                ('tipo', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], default='', max_length=10)),
                ('asientos_disponibles', models.IntegerField()),
                ('placa', models.CharField(default='', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.customuser')),
            ],
        ),
    ]
